### ISSUE TITLE
PIUIO recognized only with sudo, keep disconecting and reconnecting

### ISSUE THREAD

**Issue by martirius** [openitg/openitg#121]
If i launch openitg without super user permission it doesn't detect PIUIO, after launched with sudo it recognizes PIUIO, however it keeps disconnecting and reconnecting from the board

The screenshot of dmesg running during  oITG execution and oITG shell  
![2018-05-04-210128_1440x900_scrot](https://user-images.githubusercontent.com/17033845/39647320-bd5e9478-4fde-11e8-8541-8baafb97703b.png)

**Comment by TheKamilia** [comment]
this project is retired, please use nITG or fuck.exe by TaroNuke or SM5 by the StepMania team.

**Comment by chrispable** [comment]
You need a udev rule for your piuio

**Comment by martirius** [comment]
@chrispable 
Tried to write a udev rule:
SUBSYSTEMS=="usb", ATTRS{idVendor}=="0547", ATTRS{idProduct}=="1002", ATTRS{product}=="PIUIO", MODE:="0666",GROUP:="users"

but nothing changed. Any tips?

**Comment by martirius** [comment]
It was an electric problem, however like stated ihere: https://github.com/djpohly/piuio/issues/10 PIUIO dies for some reason sometime so it need more investigation.
