### ISSUE TITLE
Graphics Options crash (WIP2)

### ISSUE THREAD

**Issue by Chronon88** [openitg/openitg#26]
Crashes every time I go to graphics options.

Parse error in ScreenGraphicOptionsBasic::Line8

I can also put the log dump here if needed.

Running WIP2 build on Windows 7 from here: http://openitg.gr-p.com/

(Dunno which build I should run and no idea how to make it work from source. Could look into it if you point me to a right direction.)

**Comment by stubobis1** [comment]
this is still an issue for me.
