### ISSUE TITLE
OpenITG 16:9 Aspect?

### ISSUE THREAD

**Issue by ElementTimes682** [openitg/openitg#31]
We already know that if you search this on BoXoRRoXoRs, You'll find the problem about 16:9 about the 16:9 Aspect and HD Resolution. same thing with all widescreen displays. http://www.boxorroxors.com/viewtopic.php?p=6841&sid=68d979c2ac68a1536c3a76201129c7e9

**Comment by nieknooijens** [comment]
you can open Data/stepmania.ini and change the displayHeight and diwplayWidth values to 1920x1080. it'll just work! I even tested it with 4K resolution (3840x2160) and no problems at all. 8K however will crash the game!
