### ISSUE TITLE
Arcade Build Is Hopelessly Broken

### ISSUE THREAD

**Issue by terabyte** [openitg/openitg#33]
So obviously, building the arcade version in modern linux is becoming more difficult every day.  Fortunately, I think docker.io can save our bacon.  I'm working on a docker build now that will set up a docker container with the proper versions of the libraries (so it looks like an arcade cab) and spit out an arcade binary.

Wish me luck.

The other upshot here is, future hacked cabinets can use docker to run the original binary even if they are running modern linux (which is my current usecase).

**Comment by augustg** [comment]
I dont know if this is relevant to your problem, but I got the arcade build working on Debian 8.1 i386. x86_64 does not work though.

**Comment by spigwitmer** [comment]
closing because the build is not broken between @augustg's work and the ffmpeg update, though docker would cleanse the extraneous crap we have to do with debootstrap so it could warrant a ticket of its own.
