### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by ElliottBelardo** [openitg/openitg#38]
Is static.ini the same as stepmania.ini?

**Comment by LightningXCE** [comment]
Same formatting and options, however Static.ini always overrides any pre
existing settings or configurations.

You can still use Stepmania.ini as stock SM does.

**Comment by ElliottBelardo** [comment]
Yeah, but on my copy of OpenITG, I don't have stepmania.ini. Which doesn't matter, since it isn't required because I already have it. Thanks.
