### ISSUE TITLE
New cheat code discovered?

### ISSUE THREAD

**Issue by ElliottBelardo** [openitg/openitg#39]
Okay, so I press left and right, in that order, repeatedly, and then some text appears on screen. I assume this is a cheat code.

**Comment by Wanny** [comment]
Cheat codes are theme dependant. Which theme are you using?

**Comment by ElliottBelardo** [comment]
I'm using the Home theme.

**Comment by harleyknd1** [comment]
Found the cause, its an error message because pressing that order causes the system to enter demo mode repeatedly which re-adds lua scripts to the current running profile (I.E Profile P1 defined twice)
