### ISSUE TITLE
SimplyLove crashing on Boot with beta3 and master, but not beta2

### ISSUE THREAD

**Issue by concubidated** [openitg/openitg#41]
I added some debugging to OpenITG to figure out why it is crashing. There are three line causing issues in the Simple Love theme.
```
[Preferences]
SoloSingle=@PREFSMAN:GetPreference('SoloSingle')
Disqualification=@PREFSMAN:GetPreference('Disqualification')
MercifulBeginner=@PREFSMAN:GetPreference('MercifulBeginner')
```
Simply commenting these out from the metrics.ini and it boots no issues. Later in the theme there are lua calls to Get and SetPreferences for these settings that work without any issues. 

I spent a bit of time trying to track down which commit created the regression without luck, and was not able to fix it myself either. It appears that GetPreference on a preference that is a BOOL causes OpenITG to crash. I tested a few other preferences and got the same crash. 

Might be off track, but seems to be related. Figured someone with more experience with the code base know off hand what is causing this.

I know this has been a deal breaker for lots of cab owners since they all want to run this theme. Commenting out those lines seems to be a valid workaround though. 

```
OpenITG AC beta3 DEV crash report
--------------------------------------

Crash reason: Segmentation fault - address not mapped at 0x00000000
Crashed thread: Main thread

Checkpoints:
Thread: Main thread
        RageFileDriverCrypt_ITG2.cpp:190 cache
        RageFileDriverCrypt_ITG2.cpp:190 cache
        RageFileDriverCrypt_ITG2.cpp:190 cache
        RageFileDriverCrypt_ITG2.cpp:190 cache
        RageFileDriverCrypt_ITG2.cpp:190 cache

Thread: Main thread
f7270e86: __newlocale (libc.so.6)
085a41be: LuaHelpers::RunExpressionS(StdString::CStdStr<char> const&, StdString::CStdStr<char>&)
087334c5: std::string::replace(unsigned, unsigned, char const*, unsigned)
085a42e6: LuaHelpers::RunAtExpressionS(StdString::CStdStr<char>&)
085f68a4: ThemeManager::EvaluateString(StdString::CStdStr<char>&)
085f6867: ThemeManager::GetMetric(StdString::CStdStr<char> const&, StdString::CStdStr<char> const&)
085f8098: ThemeManager::LoadPreferencesFromSection(StdString::CStdStr<char> const&)
083c75cd: main
f7744cea: (libX11.so.6)
```

**Comment by terabyte** [comment]
Wow, thanks for looking into this and especially thanks for sharing your debugging findings!

**Comment by Xaero252** [comment]
This is probably an issue on the Lua side of things;
From PrefsManager.cpp we have:
`static int GetPreference( T* p, lua_State *L )
	{
		CString sName = SArg(1);
		IPreference *pPref = PREFSMAN->GetPreferenceByName( sName );
		if( pPref == NULL )
		{
			LOG->Warn( "GetPreference: unknown preference \"%s\"", sName.c_str() );
			lua_pushnil( L );
		}
		else
		{
			pPref->PushValue( L );
		}
		return 1;
	}`
Which is going to return an integer, and push a value to the Lua engine. In the case of these boolean values it's probably pushing either an integer or a bool, and Lua is expecting a string on the other side. Just a shot in the dark on what's happening - I don't know the code base as well as I should.

**Comment by augustg** [comment]
Great bug report! I found the regression and have opened a PR with a potential fix.

**Comment by concubidated** [comment]
Excellent work! I knew I was on the right track :)
