### ISSUE TITLE
vs2015 compiler issues

### ISSUE THREAD

**Issue by harleyknd1** [openitg/openitg#83]
Using visual studio 2015 getting the following errors:

Error   C1083   Cannot open include file: 'libavformat/avformat.h': No such file or directory (compiling source file arch\MovieTexture\FFMpeg_Helper.cpp)   OpenITG x:\downloads\openitg-features-vs2015\openitg-features-vs2015\src\arch\movietexture\ffmpeg_helper_common.h   13  
Error   U1073   don't know how to make 'ASM'    libpng  X:\Downloads\openitg-features-vs2015\openitg-features-vs2015\src\lpng1256\projects\visualc71\NMAKE  1  
Error   C1083   Cannot open include file: 'libavformat/avformat.h': No such file or directory (compiling source file arch\MovieTexture\MovieTexture_FFMpeg.cpp) OpenITG x:\downloads\openitg-features-vs2015\openitg-features-vs2015\src\arch\movietexture\ffmpeg_helper_common.h   13  

Any ideas why this is happening? (using the tree/features/vs2015 branch on windows 10)

**Comment by spigwitmer** [comment]
`features/vs2015` is kind of a construction site right now. When it's ready, it'll be sent out for review then merged upstream.

**Comment by spigwitmer** [comment]
VS2015 work has been merged into master awhile back. Are you still having compile issues?

**Comment by spigwitmer** [comment]
Closing. If this is still an issue, please reopen.
