### ISSUE TITLE
OpenITG for Windows crashes when entering Graphic Options

### ISSUE THREAD

**Issue by bootmii** [openitg/openitg#85]
I want to run this game windowed but I can't because I can't go into the options.

**Comment by bootmii** [comment]
I'm running Windows 10 by the way

**Comment by spigwitmer** [comment]
can you please post a crashlog?

**Comment by augustg** [comment]
Could be related to #26 and #40

**Comment by harleyknd1** [comment]
Issue fixed in Beta 3 and 4. its a known issue from Beta 2
