### ISSUE TITLE
MSVCP140D.dll is either not designed to run on Windows or it contains an error.

### ISSUE THREAD

**Issue by ARCofSpada** [openitg/openitg#86]
Tried OpenITG beta 5 and got this message when starting up.

OS: Windows 8 Embedded (x86)

**Comment by spigwitmer** [comment]
Stupidly late response. Apologies.

The .dll from that beta5-6809366 debug frankenrelease is the Win64 version, so it can't run on 32-bit architecture. Try replacing the Visual C runtime libs with the 32-bit counterparts from a VS install.

**Comment by spigwitmer** [comment]
Closing. If this is still an issue, please reopen.
